// Generated by Creer at 04:49PM on November 01, 2015 UTC, git hash: '1b69e788060071d644dd7b8745dca107577844e1'
// Two player grid based game where each player tries to burn down the other player's buildings. Let it burn!

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
// <<-- Creer-Merge: usings -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
// you can add addtional using(s) here
// <<-- /Creer-Merge: usings -->>

namespace Joueur.cs.Games.Anarchy
{
    /// <summary>
    /// Two player grid based game where each player tries to burn down the other player's buildings. Let it burn!
    /// </summary>
    class Game : BaseGame
    {
        #region Properties
        /// <summary>
        /// How many bribes players get at the beginning of their turn, not counting their burned down Buildings.
        /// </summary>
        public int BaseBribesPerTurn { get; protected set; }

        /// <summary>
        /// All the buildings in the game.
        /// </summary>
        public IList<Anarchy.Building> Buildings { get; protected set; }

        /// <summary>
        /// The current Forecast, which will be applied at the end of the turn.
        /// </summary>
        public Anarchy.Forecast CurrentForecast { get; protected set; }

        /// <summary>
        /// The player whose turn it is currently. That player can send commands. Other players cannot.
        /// </summary>
        public Anarchy.Player CurrentPlayer { get; protected set; }

        /// <summary>
        /// The current turn number, starting at 0 for the first player's turn
        /// </summary>
        public int CurrentTurn { get; protected set; }

        /// <summary>
        /// All the forecasts in the game, indexed by turn number.
        /// </summary>
        public IList<Anarchy.Forecast> Forecasts { get; protected set; }

        /// <summary>
        /// The width of the entire map along the vertical (y) axis.
        /// </summary>
        public int MapHeight { get; protected set; }

        /// <summary>
        /// The width of the entire map along the horizontal (x) axis.
        /// </summary>
        public int MapWidth { get; protected set; }

        /// <summary>
        /// The maximum amount of fire value for any Building.
        /// </summary>
        public int MaxFire { get; protected set; }

        /// <summary>
        /// The maximum amount of intensity value for any Forecast.
        /// </summary>
        public int MaxForecastIntensity { get; protected set; }

        /// <summary>
        /// The maximum number of turns before the game will automatically end.
        /// </summary>
        public int MaxTurns { get; protected set; }

        /// <summary>
        /// The next Forecast, which will be applied at the end of your opponent's turn. This is also the Forecast WeatherStations can control this turn.
        /// </summary>
        public Anarchy.Forecast NextForecast { get; protected set; }

        /// <summary>
        /// List of all the players in the game.
        /// </summary>
        public IList<Anarchy.Player> Players { get; protected set; }

        /// <summary>
        /// A unique identifier for the game instance that is being played.
        /// </summary>
        public string Session { get; protected set; }


        // <<-- Creer-Merge: properties -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
        // you can add addtional properties(s) here. None of them will be tracked or updated by the server.
        // <<-- /Creer-Merge: properties -->>
        #endregion


        #region Methods
        /// <summary>
        /// Creates a new instance of {$obj_key}. Used during game initialization, do not call directly.
        /// </summary>
        protected Game() : base()
        {
            this.Name = "Anarchy";

            this.Buildings = new List<Anarchy.Building>();
            this.Forecasts = new List<Anarchy.Forecast>();
            this.Players = new List<Anarchy.Player>();
        }


        // <<-- Creer-Merge: methods -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
        // you can add addtional method(s) here.
        // <<-- /Creer-Merge: methods -->>
        #endregion
    }
}
