// Generated by Creer at 10:46PM on October 16, 2015 UTC, git hash: '98604e3773d1933864742cb78acbf6ea0b4ecd7b'
// A player in this game. Every AI controls one player.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
// <<-- Creer-Merge: usings -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
// you can add addtional using(s) here
// <<-- /Creer-Merge: usings -->>

namespace Joueur.cs.Games.Anarchy
{
    /// <summary>
    /// A player in this game. Every AI controls one player.
    /// </summary>
    class Player : Anarchy.GameObject
    {
        #region Properties
        /// <summary>
        /// How many bribes this player has remaining to use during their turn. Each action a Building does costs 1 bribe. Any unused bribes are lost at the end of the player's turn.
        /// </summary>
        public int BribesRemaining { get; protected set; }

        /// <summary>
        /// All the buildings owned by this player.
        /// </summary>
        public IList<Anarchy.Building> Buildings { get; protected set; }

        /// <summary>
        /// What type of client this is, e.g. 'Python', 'JavaScript', or some other language. For potential data mining purposes.
        /// </summary>
        public string ClientType { get; protected set; }

        /// <summary>
        /// All the FireDepartments owned by this player.
        /// </summary>
        public IList<Anarchy.FireDepartments> FireDepartments { get; protected set; }

        /// <summary>
        /// The Warehouse that serves as this player's headquarters and has extra health. If this gets destroyed they lose.
        /// </summary>
        public Anarchy.Warehouse Headquarters { get; protected set; }

        /// <summary>
        /// if the player lost the game or not
        /// </summary>
        public bool Lost { get; protected set; }

        /// <summary>
        /// The name of the player
        /// </summary>
        public string Name { get; protected set; }

        /// <summary>
        /// All the PoliceDepartments owned by this player.
        /// </summary>
        public IList<Anarchy.PoliceDepartment> PoliceDepartments { get; protected set; }

        /// <summary>
        /// the reason why the player lost the game
        /// </summary>
        public string ReasonLost { get; protected set; }

        /// <summary>
        /// the reason why the player won the game
        /// </summary>
        public string ReasonWon { get; protected set; }

        /// <summary>
        /// The amount of time (in ns) remaining for this AI to send commands.
        /// </summary>
        public float TimeRemaining { get; protected set; }

        /// <summary>
        /// All the warehouses owned by this player. Includes the Headquarters.
        /// </summary>
        public IList<Anarchy.Warehouse> Warehouses { get; protected set; }

        /// <summary>
        /// All the WeatherStations owned by this player.
        /// </summary>
        public IList<Anarchy.WeatherStation> WeatherStations { get; protected set; }

        /// <summary>
        /// if the player won the game or not
        /// </summary>
        public bool Won { get; protected set; }


        // <<-- Creer-Merge: properties -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
        // you can add addtional properties(s) here. None of them will be tracked or updated by the server.
        // <<-- /Creer-Merge: properties -->>
        #endregion


        #region Methods
        /// <summary>
        /// Creates a new instance of {$obj_key}. Used during game initialization, do not call directly.
        /// </summary>
        protected Player() : base()
        {
            this.Buildings = new List<Anarchy.Building>();
            this.FireDepartments = new List<Anarchy.FireDepartments>();
            this.PoliceDepartments = new List<Anarchy.PoliceDepartment>();
            this.Warehouses = new List<Anarchy.Warehouse>();
            this.WeatherStations = new List<Anarchy.WeatherStation>();
        }


        // <<-- Creer-Merge: methods -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
        // you can add addtional method(s) here.
        // <<-- /Creer-Merge: methods -->>
        #endregion
    }
}
