// Generated by Creer at 06:37PM on February 15, 2016 UTC, git hash: '955970b8006ac45cc438822363db1bc1242d9868'
// Contains all details about a Piece's move in the game.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
// <<-- Creer-Merge: usings -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
// you can add addtional using(s) here
// <<-- /Creer-Merge: usings -->>

namespace Joueur.cs.Games.Chess
{
    /// <summary>
    /// Contains all details about a Piece's move in the game.
    /// </summary>
    class Move : Chess.GameObject
    {
        #region Properties
        /// <summary>
        /// The Piece captured by this Move, null if no capture.
        /// </summary>
        public Chess.Piece Captured { get; protected set; }

        /// <summary>
        /// The file the Piece moved from.
        /// </summary>
        public int FromFile { get; protected set; }

        /// <summary>
        /// The rank the Piece moved from.
        /// </summary>
        public string FromRank { get; protected set; }

        /// <summary>
        /// The Piece that was moved.
        /// </summary>
        public Chess.Piece Piece { get; protected set; }

        /// <summary>
        /// The Piece type this Move's piece was promoted to from a Pawn, empty string if no promotion occured.
        /// </summary>
        public string Promotion { get; protected set; }

        /// <summary>
        /// The standard algebraic notation (SAN) representation of the move.
        /// </summary>
        public string San { get; protected set; }

        /// <summary>
        /// The file the Piece moved to.
        /// </summary>
        public int ToFile { get; protected set; }

        /// <summary>
        /// The rank the Piece moved to.
        /// </summary>
        public string ToRank { get; protected set; }


        // <<-- Creer-Merge: properties -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
        // you can add addtional properties(s) here. None of them will be tracked or updated by the server.
        // <<-- /Creer-Merge: properties -->>
        #endregion


        #region Methods
        /// <summary>
        /// Creates a new instance of Move. Used during game initialization, do not call directly.
        /// </summary>
        protected Move() : base()
        {
        }


        // <<-- Creer-Merge: methods -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
        // you can add addtional method(s) here.
        // <<-- /Creer-Merge: methods -->>
        #endregion
    }
}
