// Generated by Creer at 01:14AM on July 22, 2015 UTC, git hash: '6ae07398e95534176c2e851c2d21269933edce81'
// A player in this game. Every AI controls one player.


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
// <<-- Creer-Merge: usings -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
// you can add addtional using(s) here
// <<-- /Creer-Merge: usings -->>

namespace Joueur.cs.Games.Checkers
{
    /// <summary>
    /// A player in this game. Every AI controls one player.
    /// </summary>
    class Player : Checkers.GameObject
    {
        #region Properties
        /// <summary>
        /// All the checkers currently in the game owned by this player
        /// </summary>
        public IList<Checkers.Checker> Checkers { get; protected set; }

        /// <summary>
        /// What type of client this is, e.g. 'Python', 'JavaScript', or some other language. For potential data mining purposes.
        /// </summary>
        public string ClientType { get; protected set; }

        /// <summary>
        /// if the player lost the game or not
        /// </summary>
        public bool Lost { get; protected set; }

        /// <summary>
        /// The name of the player
        /// </summary>
        public string Name { get; protected set; }

        /// <summary>
        /// the reason why the player lost the game
        /// </summary>
        public string ReasonLost { get; protected set; }

        /// <summary>
        /// the reason why the player won the game
        /// </summary>
        public string ReasonWon { get; protected set; }

        /// <summary>
        /// The amount of time (in ns) remaining for this AI to send commands.
        /// </summary>
        public float TimeRemaining { get; protected set; }

        /// <summary>
        /// if the player won the game or not
        /// </summary>
        public bool Won { get; protected set; }

        /// <summary>
        /// The direction your checkers must go along the y-axis until kinged
        /// </summary>
        public int YDirection { get; protected set; }


        // <<-- Creer-Merge: properties -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
        // you can add addtional properties(s) here. None of them will be tracked or updated by the server.
        // <<-- /Creer-Merge: properties -->>
        #endregion


        #region Methods
        /// <summary>
        /// Creates a new instance of {$obj_key}. Used during game initialization, do not call directly.
        /// </summary>
        protected Player() : base()
        {
            this.Checkers = new List<Checkers.Checker>();
        }


        // <<-- Creer-Merge: methods -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
        // you can add addtional method(s) here.
        // <<-- /Creer-Merge: methods -->>
        #endregion
    }
}
